<?php
//
// File generated on 2018-11-26T20:15:20+0100
// Please do not edit manually
//
MetaModel::IncludeModule('env-toolkit/core/main.php');
MetaModel::IncludeModule('env-toolkit/authent-external/model.authent-external.php');
MetaModel::IncludeModule('env-toolkit/authent-local/model.authent-local.php');
MetaModel::IncludeModule('env-toolkit/itop-attachments/model.itop-attachments.php');
MetaModel::IncludeModule('env-toolkit/itop-attachments/main.attachments.php');
MetaModel::IncludeModule('env-toolkit/itop-backup/main.itop-backup.php');
MetaModel::IncludeModule('env-toolkit/itop-config-mgmt/model.itop-config-mgmt.php');
MetaModel::IncludeModule('env-toolkit/itop-config-mgmt/main.itop-config-mgmt.php');
MetaModel::IncludeModule('env-toolkit/itop-config/main.itop-config.php');
MetaModel::IncludeModule('env-toolkit/itop-endusers-devices/model.itop-endusers-devices.php');
MetaModel::IncludeModule('env-toolkit/itop-portal-base/portal/src/entities/abstractbrick.class.inc.php');
MetaModel::IncludeModule('env-toolkit/itop-portal-base/portal/src/entities/portalbrick.class.inc.php');
MetaModel::IncludeModule('env-toolkit/itop-portal-base/portal/src/controllers/abstractcontroller.class.inc.php');
MetaModel::IncludeModule('env-toolkit/itop-portal-base/portal/src/controllers/brickcontroller.class.inc.php');
MetaModel::IncludeModule('env-toolkit/itop-portal-base/portal/src/routers/abstractrouter.class.inc.php');
MetaModel::IncludeModule('env-toolkit/itop-portal/main.itop-portal.php');
MetaModel::IncludeModule('env-toolkit/itop-profiles-itil/model.itop-profiles-itil.php');
MetaModel::IncludeModule('env-toolkit/itop-sla-computation/main.itop-sla-computation.php');
MetaModel::IncludeModule('env-toolkit/itop-storage-mgmt/model.itop-storage-mgmt.php');
MetaModel::IncludeModule('env-toolkit/itop-tickets/main.itop-tickets.php');
MetaModel::IncludeModule('env-toolkit/itop-tickets/model.itop-tickets.php');
MetaModel::IncludeModule('env-toolkit/itop-virtualization-mgmt/model.itop-virtualization-mgmt.php');
MetaModel::IncludeModule('env-toolkit/itop-welcome-itil/main.itop-welcome-itil.php');
MetaModel::IncludeModule('env-toolkit/itop-welcome-itil/model.itop-welcome-itil.php');
MetaModel::IncludeModule('env-toolkit/combodo-sla-computation/model.combodo-sla-computation.php');
MetaModel::IncludeModule('env-toolkit/itop-bridge-virtualization-storage/model.itop-bridge-virtualization-storage.php');
MetaModel::IncludeModule('env-toolkit/itop-change-mgmt-itil/model.itop-change-mgmt-itil.php');
MetaModel::IncludeModule('env-toolkit/itop-incident-mgmt-itil/model.itop-incident-mgmt-itil.php');
MetaModel::IncludeModule('env-toolkit/itop-knownerror-mgmt/model.itop-knownerror-mgmt.php');
MetaModel::IncludeModule('env-toolkit/itop-problem-mgmt/model.itop-problem-mgmt.php');
MetaModel::IncludeModule('env-toolkit/itop-request-mgmt-itil/model.itop-request-mgmt-itil.php');
MetaModel::IncludeModule('env-toolkit/itop-request-mgmt-itil/main.itop-request-mgmt-itil.php');
MetaModel::IncludeModule('env-toolkit/itop-service-mgmt-provider/model.itop-service-mgmt-provider.php');
MetaModel::IncludeModule('env-toolkit/campos cambios-module/model.campos cambios-module.php');
MetaModel::IncludeModule('env-toolkit/combodo-coverage-windows-computation-incident/main.combodo-coverage-windows-computation-incident.php');
MetaModel::IncludeModule('env-toolkit/combodo-coverage-windows-computation/main.combodo-coverage-windows-computation.php');